name: trabalho3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  image_picker: ^1.2.1
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  google_fonts: ^6.3.2
  hexcolor: ^3.0.2
  firebase_auth: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  path_provider: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
